#!/usr/bin/env tsx
/**
 * Harness asset generator — ONE canonical source (~/homer/skills/**) → native views for
 * Claude, OpenCode, Codex, plus a harness-agnostic "plain" view for scheduler contextFiles.
 *
 *   tsx scripts/render-harness-assets.ts render     # write repo mirrors under generated/harness/
 *   tsx scripts/render-harness-assets.ts check       # fail (exit 1) if mirrors drift from canonical
 *   tsx scripts/render-harness-assets.ts list        # list canonical assets
 *   tsx scripts/render-harness-assets.ts render --install   # also copy into ~/.claude, ~/.config/opencode, ~/.codex
 *
 * Authority: canonical is source of truth; generated mirrors are committed and `check` gates drift.
 * Never hand-edit generated files. Canonical assets reference LOGICAL MCP tools only; the alias
 * table (skills/aliases/mcp-tools.yaml) maps them to each harness's native tool name.
 */
import { readFileSync, writeFileSync, readdirSync, existsSync, mkdirSync, rmSync, statSync } from "fs";
import { join, dirname, relative } from "path";
import { fileURLToPath } from "url";
import { parse as parseYaml } from "yaml";

const __dirname = dirname(fileURLToPath(import.meta.url));
const HOMER = join(__dirname, "..");
const CANON = join(HOMER, "skills");
const GENERATED = join(HOMER, "generated", "harness");
const HOME = process.env.HOME ?? "";

const BANNER = (src: string) =>
  `<!-- GENERATED by scripts/render-harness-assets.ts from ${src} — DO NOT EDIT. Run \`npm run skills:render\`. -->`;

type Harness = "claude" | "opencode" | "codex";
interface AliasEntry { harness: Record<Harness, { tool: string; mcpServer?: string }>; capability?: string; requiresReview?: boolean }
interface AliasTable { logicalTools: Record<string, AliasEntry> }

interface CanonicalAsset {
  kind: "skill" | "command" | "agent";
  id: string;
  frontmatter: Record<string, any>;
  body: string;
  sourceRel: string; // path relative to repo root, for banners/errors
  sourceAbs: string;
  sourceDir: string;
}

interface RenderedFile { path: string; content: string | Buffer; installPath?: string }

function loadAliases(): AliasTable {
  const raw = readFileSync(join(CANON, "aliases", "mcp-tools.yaml"), "utf-8");
  return parseYaml(raw) as AliasTable;
}

function splitFrontmatter(text: string): { fm: Record<string, any>; body: string } {
  if (!text.startsWith("---")) throw new Error("missing frontmatter");
  const end = text.indexOf("\n---", 3);
  if (end === -1) throw new Error("unterminated frontmatter");
  const fm = parseYaml(text.slice(3, end)) as Record<string, any>;
  const body = text.slice(text.indexOf("\n", end + 1) + 1).replace(/^\n+/, "");
  return { fm, body };
}

function loadCanonicalAssets(): CanonicalAsset[] {
  const assets: CanonicalAsset[] = [];
  const dirs: Array<{ kind: CanonicalAsset["kind"]; root: string }> = [
    { kind: "skill", root: join(CANON, "skills") },
    { kind: "command", root: join(CANON, "commands") },
    { kind: "agent", root: join(CANON, "agents") },
  ];
  for (const { kind, root } of dirs) {
    if (!existsSync(root)) continue;
    for (const entry of readdirSync(root)) {
      const full = join(root, entry);
      const file = statSync(full).isDirectory()
        ? join(full, kind === "skill" ? "skill.md" : "command.md")
        : full;
      if (!existsSync(file) || !file.endsWith(".md")) continue;
      const { fm, body } = splitFrontmatter(readFileSync(file, "utf-8"));
      assets.push({
        kind,
        id: fm.id ?? entry.replace(/\.md$/, ""),
        frontmatter: fm,
        body,
        sourceRel: file.replace(HOMER + "/", ""),
        sourceAbs: file,
        sourceDir: dirname(file),
      });
    }
  }
  return assets.sort((a, b) => a.id.localeCompare(b.id));
}

/** Resolve {{tool:logical.name}} macros + return the native tool names referenced. */
function resolveBody(body: string, harness: Harness | "plain", aliases: AliasTable): { body: string; nativeTools: string[] } {
  const nativeTools: string[] = [];
  const out = body.replace(/\{\{tool:([a-z0-9_.]+)\}\}/g, (_m, logical: string) => {
    const entry = aliases.logicalTools[logical];
    if (!entry) throw new Error(`unknown logical tool "${logical}"`);
    if (harness === "plain") return logical; // harness-agnostic: keep the logical name
    const native = entry.harness[harness]?.tool;
    if (!native) throw new Error(`logical tool "${logical}" has no ${harness} alias`);
    nativeTools.push(native);
    return native;
  });
  return { body: out, nativeTools };
}

/** Native tool names for a list of logical tools (for allow-lists), harness-specific. */
function logicalToNative(logical: string[] | undefined, harness: Harness, aliases: AliasTable): string[] {
  return (logical ?? []).map((l) => {
    const entry = aliases.logicalTools[l];
    if (!entry) throw new Error(`unknown logical tool "${l}"`);
    const native = entry.harness[harness]?.tool;
    if (!native) throw new Error(`logical tool "${l}" has no ${harness} alias`);
    return native;
  });
}

function yamlFrontmatter(obj: Record<string, any>): string {
  const lines: string[] = ["---"];
  for (const [k, v] of Object.entries(obj)) {
    if (v === undefined || v === null) continue;
    if (Array.isArray(v)) {
      if (v.length === 0) continue;
      // Claude `allowed-tools` is a comma-joined scalar; everything else is a YAML list.
      if (k === "allowed-tools") lines.push(`${k}: ${v.join(", ")}`);
      else { lines.push(`${k}:`); for (const item of v) lines.push(`  - ${item}`); }
    } else if (typeof v === "boolean") {
      lines.push(`${k}: ${v}`);
    } else {
      lines.push(`${k}: ${v}`);
    }
  }
  lines.push("---");
  return lines.join("\n");
}

function toolList(value: unknown): string[] {
  if (Array.isArray(value)) return value.map(String).map((v) => v.trim()).filter(Boolean);
  if (typeof value === "string") return value.split(",").map((v) => v.trim()).filter(Boolean);
  return [];
}

function asBuffer(content: string | Buffer): Buffer {
  return Buffer.isBuffer(content) ? content : Buffer.from(content);
}

function renderResourceFiles(a: CanonicalAsset, targetDir: string, installDir?: string): RenderedFile[] {
  const files: RenderedFile[] = [];
  const walk = (dir: string) => {
    for (const entry of readdirSync(dir)) {
      if (entry === ".DS_Store" || entry === "__pycache__") continue;
      const file = join(dir, entry);
      const stat = statSync(file);
      if (stat.isDirectory()) {
        walk(file);
        continue;
      }
      if (file === a.sourceAbs) continue;
      const rel = relative(a.sourceDir, file);
      files.push({
        path: join(targetDir, rel),
        content: readFileSync(file),
        installPath: installDir ? join(installDir, rel) : undefined,
      });
    }
  };
  walk(a.sourceDir);
  return files;
}

// ── Renderers ────────────────────────────────────────────────────────────────────────────
function renderClaude(a: CanonicalAsset, aliases: AliasTable): RenderedFile[] {
  const h = a.frontmatter.harness?.claude ?? {};
  const files: RenderedFile[] = [];
  const { body, nativeTools } = resolveBody(a.body, "claude", aliases);
  const allowed = Array.from(new Set([
    ...toolList(a.frontmatter["allowed-tools"]),
    ...toolList(h.allowedTools),
    ...logicalToNative(a.frontmatter.tools?.logical, "claude", aliases),
    ...nativeTools,
  ]));

  if (a.kind === "skill" && (h.emitSkill ?? true)) {
    const targetDir = join(GENERATED, "claude", "skills", a.id);
    const installDir = join(HOME, ".claude", "skills", a.id);
    const fm = yamlFrontmatter({
      name: a.id,
      description: a.frontmatter.description,
      "allowed-tools": allowed,
      "disable-model-invocation": h.disableModelInvocation ?? a.frontmatter.execution?.disableModelInvocation,
    });
    files.push({
      path: join(targetDir, "SKILL.md"),
      content: `${BANNER(a.sourceRel)}\n${fm}\n\n${body}`,
      installPath: join(installDir, "SKILL.md"),
    });
    files.push(...renderResourceFiles(a, targetDir, installDir));
  }
  if (a.kind === "command" && (h.emitCommand ?? true)) {
    const fm = yamlFrontmatter({
      "allowed-tools": allowed,
      description: a.frontmatter.description,
      "argument-hint": a.frontmatter.arguments?.hint,
    });
    files.push({
      path: join(GENERATED, "claude", "commands", `${a.id}.md`),
      content: `${BANNER(a.sourceRel)}\n${fm}\n\n${body}`,
      installPath: join(HOME, ".claude", "commands", `${a.id}.md`),
    });
  }
  return files;
}

function renderOpenCode(a: CanonicalAsset, aliases: AliasTable): RenderedFile[] {
  const h = a.frontmatter.harness?.opencode ?? {};
  const files: RenderedFile[] = [];
  const { body } = resolveBody(a.body, "opencode", aliases);
  if (a.kind === "skill" && (h.emitSkill ?? true)) {
    const targetDir = join(GENERATED, "opencode", "skills", a.id);
    const installDir = join(HOME, ".config", "opencode", "skills", a.id);
    const fm = yamlFrontmatter({ name: a.id, description: a.frontmatter.description });
    files.push({
      path: join(targetDir, "SKILL.md"),
      content: `${BANNER(a.sourceRel)}\n${fm}\n\n${body}`,
      installPath: join(installDir, "SKILL.md"),
    });
    files.push(...renderResourceFiles(a, targetDir, installDir));
  }
  if ((a.kind === "command" && (h.emitCommand ?? true)) || (a.kind === "skill" && a.frontmatter.triggers?.slash && h.emitCommand)) {
    const fm = yamlFrontmatter({ description: a.frontmatter.description, "argument-hint": a.frontmatter.arguments?.hint });
    files.push({
      path: join(GENERATED, "opencode", "command", `${a.id}.md`),
      content: `${BANNER(a.sourceRel)}\n${fm}\n\n${body}`,
      installPath: join(HOME, ".config", "opencode", "command", `${a.id}.md`),
    });
  }
  return files;
}

function renderCodex(a: CanonicalAsset, aliases: AliasTable): RenderedFile[] {
  const h = a.frontmatter.harness?.codex ?? {};
  const files: RenderedFile[] = [];
  const { body } = resolveBody(a.body, "codex", aliases);
  // Codex has no ~/.codex/prompts: commands render as skills with a slash-trigger note in the body.
  const emitSkill = h.emitSkill ?? (a.kind === "skill");
  if (emitSkill) {
    const targetDir = join(GENERATED, "codex", "skills", a.id);
    const installDir = join(HOME, ".codex", "skills", "homer", a.id);
    const slash = a.frontmatter.triggers?.slash?.[0];
    const desc = a.kind === "command" && slash ? `${a.frontmatter.description} (invoke: ${slash})` : a.frontmatter.description;
    const fm = yamlFrontmatter({ name: a.id, description: desc });
    files.push({
      path: join(targetDir, "SKILL.md"),
      // Codex requires YAML frontmatter on line 1, so the banner goes below it (unlike claude/opencode).
      content: `${fm}\n\n${BANNER(a.sourceRel)}\n\n${body}`,
      installPath: join(installDir, "SKILL.md"),
    });
    if (a.kind === "skill") files.push(...renderResourceFiles(a, targetDir, installDir));
  }
  return files;
}

/** Plain, scheduler-safe view: body only, logical tool names (no native MCP names), no frontmatter. */
function renderPlain(a: CanonicalAsset, aliases: AliasTable): RenderedFile[] {
  if (a.kind !== "skill") return [];
  const { body } = resolveBody(a.body, "plain", aliases);
  // Add a title only if the body doesn't already open with its own H1 (avoids a duplicate heading).
  const heading = /^#\s+/.test(body.trimStart()) ? "" : `# ${a.frontmatter.title ?? a.id}\n\n`;
  return [{
    path: join(GENERATED, "plain", `${a.id}.md`),
    content: `${BANNER(a.sourceRel)}\n\n${heading}${body}`,
    installPath: join(HOMER, "skills", "dist", "plain", `${a.id}.md`),
  }];
}

function renderAll(): RenderedFile[] {
  const aliases = loadAliases();
  const assets = loadCanonicalAssets();
  const out: RenderedFile[] = [];
  for (const a of assets) {
    out.push(...renderClaude(a, aliases), ...renderOpenCode(a, aliases), ...renderCodex(a, aliases), ...renderPlain(a, aliases));
  }
  return out;
}

// ── Commands ─────────────────────────────────────────────────────────────────────────────
function cmdRender(install: boolean) {
  const files = renderAll();
  if (existsSync(GENERATED)) rmSync(GENERATED, { recursive: true, force: true });
  for (const f of files) {
    mkdirSync(dirname(f.path), { recursive: true });
    writeFileSync(f.path, f.content);
    if (install && f.installPath) {
      mkdirSync(dirname(f.installPath), { recursive: true });
      writeFileSync(f.installPath, f.content);
    }
  }
  console.log(`Rendered ${files.length} files for ${loadCanonicalAssets().length} canonical assets → ${GENERATED.replace(HOME, "~")}`);
  if (install) console.log("Installed into harness-native home directories.");
}

function cmdCheck(): number {
  const files = renderAll();
  const drift: string[] = [];
  for (const f of files) {
    const onDisk = existsSync(f.path) ? readFileSync(f.path) : null;
    if (!onDisk || Buffer.compare(onDisk, asBuffer(f.content)) !== 0) drift.push(f.path.replace(HOME, "~"));
  }
  // Also flag committed files with no canonical source (stale).
  const expected = new Set(files.map((f) => f.path));
  const walk = (dir: string) => { if (!existsSync(dir)) return; for (const e of readdirSync(dir)) { const p = join(dir, e); statSync(p).isDirectory() ? walk(p) : (!expected.has(p) && drift.push(`STALE ${p.replace(HOME, "~")}`)); } };
  walk(GENERATED);
  if (drift.length) {
    console.error(`skills:check FAILED — ${drift.length} file(s) drifted from canonical. Run \`npm run skills:render\`:`);
    for (const d of drift) console.error(`  ${d}`);
    return 1;
  }
  console.log(`skills:check OK — ${files.length} generated files match canonical.`);
  return 0;
}

function cmdList() {
  for (const a of loadCanonicalAssets()) console.log(`${a.kind.padEnd(8)} ${a.id.padEnd(24)} ${a.sourceRel}`);
}

const [cmd, ...rest] = process.argv.slice(2);
try {
  if (cmd === "render") cmdRender(rest.includes("--install"));
  else if (cmd === "check") process.exit(cmdCheck());
  else if (cmd === "list") cmdList();
  else { console.error("usage: render-harness-assets.ts <render [--install] | check | list>"); process.exit(2); }
} catch (e) {
  console.error(`render-harness-assets: ${e instanceof Error ? e.message : e}`);
  process.exit(1);
}
