#!/usr/bin/env tsx
/**
 * Harness asset generator — canonical skill roots → native views for
 * Claude, OpenCode, Codex, plus a harness-agnostic "plain" view for scheduler contextFiles.
 *
 *   tsx scripts/render-harness-assets.ts render     # write repo mirrors under generated/harness/
 *   tsx scripts/render-harness-assets.ts check       # fail (exit 1) if mirrors drift from canonical
 *   tsx scripts/render-harness-assets.ts list        # list canonical assets
 *   tsx scripts/render-harness-assets.ts render --install   # also copy into ~/.claude, ~/.config/opencode, ~/.codex
 *
 * Authority: canonical is source of truth; generated mirrors are committed and `check` gates drift.
 * Never hand-edit generated files. Canonical assets reference LOGICAL MCP tools only; the alias
 * table (skills/aliases/mcp-tools.yaml) maps them to each harness's native tool name.
 */
import { readFileSync, writeFileSync, readdirSync, existsSync, mkdirSync, rmSync, statSync } from "fs";
import { join, dirname, relative, resolve } from "path";
import { fileURLToPath } from "url";
import { parse as parseYaml } from "yaml";

const __dirname = dirname(fileURLToPath(import.meta.url));
const HOMER = join(__dirname, "..");
const HOME = process.env.HOME ?? "";
const ROOTS_CONFIG = process.env.HOMER_SKILL_ROOTS_CONFIG ?? join(HOME, ".config", "homer", "skill-roots.json");

const BANNER = (src: string) =>
  `<!-- GENERATED by scripts/render-harness-assets.ts from ${src} — DO NOT EDIT. Run \`npm run skills:render\`. -->`;

type Harness = "claude" | "opencode" | "codex";
interface AliasEntry { harness: Record<Harness, { tool: string; mcpServer?: string }>; capability?: string; requiresReview?: boolean }
interface AliasTable { logicalTools: Record<string, AliasEntry> }

interface CanonicalRoot {
  path: string;
  canonicalDir: string;
  generatedDir: string;
  exclude: Set<string>;
}

interface CanonicalAsset {
  kind: "skill" | "command" | "agent";
  id: string;
  frontmatter: Record<string, any>;
  body: string;
  sourceRel: string; // display path for banners/list output
  sourceAbs: string;
  sourceDir: string;
  root: CanonicalRoot;
}

interface RenderedFile { path: string; content: string | Buffer; installPath?: string }

function homePath(path: string): string {
  if (!HOME) return path;
  return path === HOME ? "~" : path.startsWith(HOME + "/") ? `~${path.slice(HOME.length)}` : path;
}

function loadRoots(): { roots: CanonicalRoot[]; configured: boolean } {
  if (!existsSync(ROOTS_CONFIG)) {
    return {
      roots: [{ path: HOMER, canonicalDir: join(HOMER, "skills"), generatedDir: join(HOMER, "generated", "harness"), exclude: new Set() }],
      configured: false,
    };
  }

  const parsed = JSON.parse(readFileSync(ROOTS_CONFIG, "utf-8")) as { roots?: unknown };
  if (!Array.isArray(parsed.roots) || parsed.roots.length === 0) {
    throw new Error(`${homePath(ROOTS_CONFIG)} must contain a non-empty "roots" array`);
  }
  const roots = parsed.roots.map((entry, index): CanonicalRoot => {
    const path = typeof entry === "string"
      ? entry
      : entry && typeof entry === "object" && typeof (entry as { path?: unknown }).path === "string"
        ? (entry as { path: string }).path
        : null;
    const exclude = typeof entry === "object" && entry !== null ? (entry as { exclude?: unknown }).exclude : undefined;
    if (!path) throw new Error(`${homePath(ROOTS_CONFIG)} roots[${index}] must be a path string or an object with a string "path"`);
    if (exclude !== undefined && (!Array.isArray(exclude) || exclude.some((id) => typeof id !== "string"))) {
      throw new Error(`${homePath(ROOTS_CONFIG)} roots[${index}].exclude must be an array of asset ids`);
    }
    const rootPath = resolve(path);
    return {
      path: rootPath,
      canonicalDir: join(rootPath, "skills"),
      generatedDir: join(rootPath, "generated", "harness"),
      exclude: new Set(exclude as string[] | undefined),
    };
  });
  return { roots, configured: true };
}

function loadAliases(root: CanonicalRoot): AliasTable {
  const raw = readFileSync(join(root.canonicalDir, "aliases", "mcp-tools.yaml"), "utf-8");
  return parseYaml(raw) as AliasTable;
}

function splitFrontmatter(text: string): { fm: Record<string, any>; body: string } {
  if (!text.startsWith("---")) throw new Error("missing frontmatter");
  const end = text.indexOf("\n---", 3);
  if (end === -1) throw new Error("unterminated frontmatter");
  const fm = parseYaml(text.slice(3, end)) as Record<string, any>;
  const body = text.slice(text.indexOf("\n", end + 1) + 1).replace(/^\n+/, "");
  return { fm, body };
}

function loadCanonicalAssets(roots: CanonicalRoot[], configured: boolean): CanonicalAsset[] {
  const assets: CanonicalAsset[] = [];
  const byId = new Map<string, CanonicalAsset>();
  for (const root of roots) {
    const dirs: Array<{ kind: CanonicalAsset["kind"]; path: string }> = [
      { kind: "skill", path: join(root.canonicalDir, "skills") },
      { kind: "command", path: join(root.canonicalDir, "commands") },
      { kind: "agent", path: join(root.canonicalDir, "agents") },
    ];
    for (const { kind, path } of dirs) {
      if (!existsSync(path)) continue;
      for (const entry of readdirSync(path)) {
        const full = join(path, entry);
        const file = statSync(full).isDirectory()
          ? join(full, kind === "skill" ? "skill.md" : "command.md")
          : full;
        if (!existsSync(file) || !file.endsWith(".md")) continue;
        const { fm, body } = splitFrontmatter(readFileSync(file, "utf-8"));
        const id = fm.id ?? entry.replace(/\.md$/, "");
        if (root.exclude.has(id)) continue;
        const asset: CanonicalAsset = {
          kind,
          id,
          frontmatter: fm,
          body,
          sourceRel: configured ? homePath(file) : relative(root.path, file),
          sourceAbs: file,
          sourceDir: dirname(file),
          root,
        };
        const duplicate = byId.get(id);
        if (duplicate) {
          throw new Error(`duplicate asset id "${id}": ${homePath(duplicate.sourceAbs)} and ${homePath(file)}`);
        }
        byId.set(id, asset);
        assets.push(asset);
      }
    }
  }
  return assets.sort((a, b) => a.id.localeCompare(b.id));
}

/** Resolve {{tool:logical.name}} macros + return the native tool names referenced. */
function resolveBody(body: string, harness: Harness | "plain", aliases: AliasTable): { body: string; nativeTools: string[] } {
  const nativeTools: string[] = [];
  const out = body.replace(/\{\{tool:([a-z0-9_.]+)\}\}/g, (_m, logical: string) => {
    const entry = aliases.logicalTools[logical];
    if (!entry) throw new Error(`unknown logical tool "${logical}"`);
    if (harness === "plain") return logical; // harness-agnostic: keep the logical name
    const native = entry.harness[harness]?.tool;
    if (!native) throw new Error(`logical tool "${logical}" has no ${harness} alias`);
    nativeTools.push(native);
    return native;
  });
  return { body: out, nativeTools };
}

/** Native tool names for a list of logical tools (for allow-lists), harness-specific. */
function logicalToNative(logical: string[] | undefined, harness: Harness, aliases: AliasTable): string[] {
  return (logical ?? []).map((l) => {
    const entry = aliases.logicalTools[l];
    if (!entry) throw new Error(`unknown logical tool "${l}"`);
    const native = entry.harness[harness]?.tool;
    if (!native) throw new Error(`logical tool "${l}" has no ${harness} alias`);
    return native;
  });
}

function yamlFrontmatter(obj: Record<string, any>): string {
  const lines: string[] = ["---"];
  for (const [k, v] of Object.entries(obj)) {
    if (v === undefined || v === null) continue;
    if (Array.isArray(v)) {
      if (v.length === 0) continue;
      // Claude `allowed-tools` is a comma-joined scalar; everything else is a YAML list.
      if (k === "allowed-tools") lines.push(`${k}: ${v.join(", ")}`);
      else { lines.push(`${k}:`); for (const item of v) lines.push(`  - ${item}`); }
    } else if (typeof v === "boolean") {
      lines.push(`${k}: ${v}`);
    } else {
      lines.push(`${k}: ${v}`);
    }
  }
  lines.push("---");
  return lines.join("\n");
}

function toolList(value: unknown): string[] {
  if (Array.isArray(value)) return value.map(String).map((v) => v.trim()).filter(Boolean);
  if (typeof value === "string") return value.split(",").map((v) => v.trim()).filter(Boolean);
  return [];
}

function asBuffer(content: string | Buffer): Buffer {
  return Buffer.isBuffer(content) ? content : Buffer.from(content);
}

function renderResourceFiles(a: CanonicalAsset, targetDir: string, installDir?: string): RenderedFile[] {
  const files: RenderedFile[] = [];
  const walk = (dir: string) => {
    for (const entry of readdirSync(dir)) {
      if (entry === ".DS_Store" || entry === "__pycache__") continue;
      const file = join(dir, entry);
      const stat = statSync(file);
      if (stat.isDirectory()) {
        walk(file);
        continue;
      }
      if (file === a.sourceAbs) continue;
      const rel = relative(a.sourceDir, file);
      files.push({
        path: join(targetDir, rel),
        content: readFileSync(file),
        installPath: installDir ? join(installDir, rel) : undefined,
      });
    }
  };
  walk(a.sourceDir);
  return files;
}

// ── Renderers ────────────────────────────────────────────────────────────────────────────
function renderClaude(a: CanonicalAsset, aliases: AliasTable): RenderedFile[] {
  const h = a.frontmatter.harness?.claude ?? {};
  const files: RenderedFile[] = [];
  const { body, nativeTools } = resolveBody(a.body, "claude", aliases);
  const allowed = Array.from(new Set([
    ...toolList(a.frontmatter["allowed-tools"]),
    ...toolList(h.allowedTools),
    ...logicalToNative(a.frontmatter.tools?.logical, "claude", aliases),
    ...nativeTools,
  ]));

  if (a.kind === "skill" && (h.emitSkill ?? true)) {
    const targetDir = join(a.root.generatedDir, "claude", "skills", a.id);
    const installDir = join(HOME, ".claude", "skills", a.id);
    const fm = yamlFrontmatter({
      name: a.id,
      description: a.frontmatter.description,
      "allowed-tools": allowed,
      "disable-model-invocation": h.disableModelInvocation ?? a.frontmatter.execution?.disableModelInvocation,
    });
    files.push({
      path: join(targetDir, "SKILL.md"),
      content: `${fm}\n\n${BANNER(a.sourceRel)}\n\n${body}`,
      installPath: join(installDir, "SKILL.md"),
    });
    files.push(...renderResourceFiles(a, targetDir, installDir));
  }
  if (a.kind === "command" && (h.emitCommand ?? true)) {
    const fm = yamlFrontmatter({
      "allowed-tools": allowed,
      description: a.frontmatter.description,
      "argument-hint": a.frontmatter.arguments?.hint,
    });
    files.push({
      path: join(a.root.generatedDir, "claude", "commands", `${a.id}.md`),
      content: `${fm}\n\n${BANNER(a.sourceRel)}\n\n${body}`,
      installPath: join(HOME, ".claude", "commands", `${a.id}.md`),
    });
  }
  return files;
}

function renderOpenCode(a: CanonicalAsset, aliases: AliasTable): RenderedFile[] {
  const h = a.frontmatter.harness?.opencode ?? {};
  const files: RenderedFile[] = [];
  const { body } = resolveBody(a.body, "opencode", aliases);
  if (a.kind === "skill" && (h.emitSkill ?? true)) {
    const targetDir = join(a.root.generatedDir, "opencode", "skills", a.id);
    const installDir = join(HOME, ".config", "opencode", "skills", a.id);
    const fm = yamlFrontmatter({ name: a.id, description: a.frontmatter.description });
    files.push({
      path: join(targetDir, "SKILL.md"),
      content: `${fm}\n\n${BANNER(a.sourceRel)}\n\n${body}`,
      installPath: join(installDir, "SKILL.md"),
    });
    files.push(...renderResourceFiles(a, targetDir, installDir));
  }
  if ((a.kind === "command" && (h.emitCommand ?? true)) || (a.kind === "skill" && a.frontmatter.triggers?.slash && h.emitCommand)) {
    const fm = yamlFrontmatter({ description: a.frontmatter.description, "argument-hint": a.frontmatter.arguments?.hint });
    files.push({
      path: join(a.root.generatedDir, "opencode", "command", `${a.id}.md`),
      content: `${fm}\n\n${BANNER(a.sourceRel)}\n\n${body}`,
      installPath: join(HOME, ".config", "opencode", "command", `${a.id}.md`),
    });
  }
  return files;
}

function renderCodex(a: CanonicalAsset, aliases: AliasTable): RenderedFile[] {
  const h = a.frontmatter.harness?.codex ?? {};
  const files: RenderedFile[] = [];
  const { body } = resolveBody(a.body, "codex", aliases);
  // Commands explicitly enabled for Codex render as skills with a slash-trigger note in the body.
  const emitSkill = h.emitSkill ?? (a.kind === "skill");
  if (emitSkill) {
    const targetDir = join(a.root.generatedDir, "codex", "skills", a.id);
    const installDir = join(HOME, ".codex", "skills", "homer", a.id);
    const slash = a.frontmatter.triggers?.slash?.[0];
    const desc = a.kind === "command" && slash ? `${a.frontmatter.description} Invoke with ${slash}.` : a.frontmatter.description;
    const fm = yamlFrontmatter({ name: a.id, description: desc });
    files.push({
      path: join(targetDir, "SKILL.md"),
      // YAML frontmatter must start on line 1 in every harness, so the banner goes below it.
      content: `${fm}\n\n${BANNER(a.sourceRel)}\n\n${body}`,
      installPath: join(installDir, "SKILL.md"),
    });
    if (a.kind === "skill") files.push(...renderResourceFiles(a, targetDir, installDir));
  }
  return files;
}

/** Plain, scheduler-safe view: body only, logical tool names (no native MCP names), no frontmatter. */
function renderPlain(a: CanonicalAsset, aliases: AliasTable): RenderedFile[] {
  if (a.kind !== "skill") return [];
  const { body } = resolveBody(a.body, "plain", aliases);
  // Add a title only if the body doesn't already open with its own H1 (avoids a duplicate heading).
  const heading = /^#\s+/.test(body.trimStart()) ? "" : `# ${a.frontmatter.title ?? a.id}\n\n`;
  return [{
    path: join(a.root.generatedDir, "plain", `${a.id}.md`),
    content: `${BANNER(a.sourceRel)}\n\n${heading}${body}`,
    installPath: join(a.root.canonicalDir, "dist", "plain", `${a.id}.md`),
  }];
}

function renderAll(roots: CanonicalRoot[], configured: boolean): { files: RenderedFile[]; assets: CanonicalAsset[] } {
  const aliases = loadAliases(roots[0]!);
  const assets = loadCanonicalAssets(roots, configured);
  const out: RenderedFile[] = [];
  for (const a of assets) {
    out.push(...renderClaude(a, aliases), ...renderOpenCode(a, aliases), ...renderCodex(a, aliases), ...renderPlain(a, aliases));
  }
  return { files: out, assets };
}

// ── Commands ─────────────────────────────────────────────────────────────────────────────
function cmdRender(install: boolean) {
  const { roots, configured } = loadRoots();
  const { files, assets } = renderAll(roots, configured);
  for (const root of roots) {
    if (existsSync(root.generatedDir)) rmSync(root.generatedDir, { recursive: true, force: true });
  }
  for (const f of files) {
    mkdirSync(dirname(f.path), { recursive: true });
    writeFileSync(f.path, f.content);
    if (install && f.installPath) {
      mkdirSync(dirname(f.installPath), { recursive: true });
      writeFileSync(f.installPath, f.content);
    }
  }
  if (!configured) console.log(`Rendered ${files.length} files for ${assets.length} canonical assets → ${homePath(roots[0]!.generatedDir)}`);
  else {
    console.log(`Rendered ${files.length} files for ${assets.length} canonical assets across ${roots.length} roots:`);
    for (const root of roots) console.log(`  ${homePath(root.path)} → ${homePath(root.generatedDir)}`);
  }
  if (install) console.log("Installed into harness-native home directories.");
}

function cmdCheck(): number {
  const { roots, configured } = loadRoots();
  const { files } = renderAll(roots, configured);
  const drift: string[] = [];
  for (const f of files) {
    const onDisk = existsSync(f.path) ? readFileSync(f.path) : null;
    if (!onDisk || Buffer.compare(onDisk, asBuffer(f.content)) !== 0) drift.push(f.path.replace(HOME, "~"));
  }
  // Also flag committed files with no canonical source (stale).
  const expected = new Set(files.map((f) => f.path));
  const walk = (dir: string) => { if (!existsSync(dir)) return; for (const e of readdirSync(dir)) { const p = join(dir, e); statSync(p).isDirectory() ? walk(p) : (!expected.has(p) && drift.push(`STALE ${p.replace(HOME, "~")}`)); } };
  for (const root of roots) walk(root.generatedDir);
  if (drift.length) {
    console.error(`skills:check FAILED — ${drift.length} file(s) drifted from canonical. Run \`npm run skills:render\`:`);
    for (const d of drift) console.error(`  ${d}`);
    return 1;
  }
  console.log(`skills:check OK — ${files.length} generated files match canonical.`);
  return 0;
}

function cmdList() {
  const { roots, configured } = loadRoots();
  for (const a of loadCanonicalAssets(roots, configured)) {
    const root = configured ? ` ${homePath(a.root.path)}` : "";
    console.log(`${a.kind.padEnd(8)} ${a.id.padEnd(24)} ${a.sourceRel}${root}`);
  }
}

const [cmd, ...rest] = process.argv.slice(2);
try {
  if (cmd === "render") cmdRender(rest.includes("--install"));
  else if (cmd === "check") process.exit(cmdCheck());
  else if (cmd === "list") cmdList();
  else { console.error("usage: render-harness-assets.ts <render [--install] | check | list>"); process.exit(2); }
} catch (e) {
  console.error(`render-harness-assets: ${e instanceof Error ? e.message : e}`);
  process.exit(1);
}
