/**
 * Context Bridge — generates homer-context.md for Claude Code auto-memory
 *
 * Runs at 02:30 daily (30 min after nightly-memory) to produce a snapshot
 * of Homer's state that Claude Code sessions can read via auto-memory.
 *
 * Sources: me.md goals, work.md active projects, recent promoted facts,
 * active plans, and pending outcome checks.
 */

import { writeFileSync, mkdirSync, existsSync, renameSync, readdirSync } from "fs";
import { join } from "path";
import { extractCurrentGoals, extractActiveProjects } from "../shared-context.js";
import { StateManager } from "../../state/manager.js";
import { logger } from "../../utils/logger.js";
import { PATHS } from "../../config/paths.js";

const OUTPUT_DIR = PATHS.autoMemoryDir;
const OUTPUT_FILE = join(OUTPUT_DIR, "homer-context.md");
const MAX_LINES = 150;

export async function runContextBridge(
  stateManager?: StateManager
): Promise<{ success: boolean; output: string; error?: string }> {
  try {
    const sm = stateManager ?? new StateManager(PATHS.db);
    const ownSm = !stateManager;

    try {
      const sections: string[] = [];

      sections.push("<!-- Generated by Homer daemon. Do not edit. -->");
      sections.push(`<!-- Updated: ${new Date().toISOString()} -->`);
      sections.push("");
      sections.push("# Homer Context");
      sections.push("");

      // Current goals from me.md
      const goals = await extractCurrentGoals();
      if (!goals.startsWith("(")) {
        sections.push("## Current Goals");
        sections.push(goals);
        sections.push("");
      }

      // Active projects from work.md
      const projects = await extractActiveProjects();
      if (!projects.startsWith("(")) {
        sections.push("## Active Projects");
        sections.push(projects);
        sections.push("");
      }

      // Recent promoted facts (last 7 days)
      try {
        const facts = sm.getRecentPromotedFacts(7);
        if (facts.length > 0) {
          sections.push("## Recent Memory Promotions (7d)");
          for (const fact of facts.slice(0, 15)) {
            const date = fact.promotedAt.slice(0, 10);
            const target = fact.targetFile;
            const snippet = fact.content.length > 120
              ? fact.content.slice(0, 120) + "..."
              : fact.content;
            sections.push(`- [${date}] → ${target}: ${snippet}`);
          }
          sections.push("");
        }
      } catch {
        // promoted_facts table may not exist yet
      }

      // Active plans
      const plansDir = PATHS.plans;
      if (existsSync(plansDir)) {
        try {
          const planFiles = readdirSync(plansDir)
            .filter(f => f.endsWith(".md") && f !== "archive");
          if (planFiles.length > 0) {
            sections.push("## Active Plans");
            for (const file of planFiles.slice(0, 10)) {
              const name = file.replace(/\.md$/, "").replace(/-/g, " ");
              sections.push(`- ${name}`);
            }
            sections.push("");
          }
        } catch {
          // plans dir read error
        }
      }

      // Pending outcome checks
      try {
        const pending = sm.getDb().prepare(`
          SELECT source_title, check_at
          FROM outcome_checks
          WHERE status = 'pending' AND check_at <= datetime('now', '+7 days')
          ORDER BY check_at ASC LIMIT 5
        `).all() as Array<{ source_title: string; check_at: string }>;

        if (pending.length > 0) {
          sections.push("## Pending Outcome Checks");
          for (const oc of pending) {
            sections.push(`- [${oc.check_at.slice(0, 10)}] ${oc.source_title}`);
          }
          sections.push("");
        }
      } catch {
        // outcome_checks table may not exist
      }

      // Build output, enforce line limit
      let content = sections.join("\n");
      const lines = content.split("\n");
      if (lines.length > MAX_LINES) {
        content = lines.slice(0, MAX_LINES).join("\n") + "\n\n<!-- Truncated to 150 lines -->\n";
      }

      // Atomic write: temp file + rename
      if (!existsSync(OUTPUT_DIR)) {
        mkdirSync(OUTPUT_DIR, { recursive: true });
      }
      const tmpPath = OUTPUT_FILE + ".tmp";
      writeFileSync(tmpPath, content, "utf-8");
      renameSync(tmpPath, OUTPUT_FILE);

      const lineCount = content.split("\n").length;
      logger.info({ lineCount, outputFile: OUTPUT_FILE }, "Context bridge file generated");

      return {
        success: true,
        output: `Generated homer-context.md (${lineCount} lines)`,
      };
    } finally {
      if (ownSm) sm.close();
    }
  } catch (error) {
    const msg = error instanceof Error ? error.message : String(error);
    logger.error({ error: msg }, "Context bridge failed");
    return { success: false, output: "", error: msg };
  }
}

// CLI entry point for direct tsx/node execution (used by hook fallback)
const isMain = import.meta.url === `file://${process.argv[1]}`
  || process.argv[1]?.endsWith("/context-bridge.js");
if (isMain) {
  runContextBridge().then(r => {
    console.log(r.output);
    process.exit(r.success ? 0 : 1);
  });
}
