/**
 * Context Bridge — generates Homer zone in MEMORY.md for Claude Code auto-memory
 *
 * Runs at 02:30 daily (30 min after nightly-memory) and on SessionStart/Stop hooks.
 * Produces a snapshot of Homer's state within sentinel markers, preserving any
 * Claude Code auto-memory content outside the markers.
 *
 * Sources: me.md goals, work.md active projects, recent promoted facts,
 * active plans, and pending outcome checks.
 */

import { writeFileSync, readFileSync, mkdirSync, existsSync, renameSync, readdirSync, unlinkSync } from "fs";
import { join } from "path";
import { extractCurrentGoals, extractActiveProjects } from "../shared-context.js";
import { StateManager } from "../../state/manager.js";
import { logger } from "../../utils/logger.js";
import { PATHS } from "../../config/paths.js";

const HOMER_START = "<!-- HOMER:START — auto-generated by Homer daemon, do not edit -->";
const HOMER_END = "<!-- HOMER:END -->";
const HOMER_MAX_LINES = 120;

const TARGET_DIRS = [
  PATHS.autoMemoryDir,                                      // -Users-yj (home dir sessions)
  join(PATHS.claudeDir, "projects/-Users-yj-homer/memory"), // Homer dev sessions
];

function wrapWithSentinels(content: string): string {
  return `${HOMER_START}\n${content}\n${HOMER_END}`;
}

function mergeWithExisting(homerContent: string, memoryPath: string): string {
  if (!existsSync(memoryPath)) return wrapWithSentinels(homerContent);

  const existing = readFileSync(memoryPath, "utf-8");
  const startIdx = existing.indexOf(HOMER_START);
  const endIdx = existing.indexOf(HOMER_END);

  let claudeContent: string;
  if (startIdx >= 0 && endIdx >= 0) {
    const before = existing.slice(0, startIdx).trim();
    const after = existing.slice(endIdx + HOMER_END.length).trim();
    claudeContent = [before, after].filter(Boolean).join("\n\n");
  } else {
    // No existing markers — treat entire file as Claude-managed content
    claudeContent = existing.trim();
  }

  return wrapWithSentinels(homerContent) + (claudeContent ? "\n\n" + claudeContent : "");
}

export async function runContextBridge(
  stateManager?: StateManager
): Promise<{ success: boolean; output: string; error?: string }> {
  try {
    const sm = stateManager ?? new StateManager(PATHS.db);
    const ownSm = !stateManager;

    try {
      const sections: string[] = [];

      sections.push(`<!-- Updated: ${new Date().toISOString()} -->`);
      sections.push("");
      sections.push("# Homer Context");
      sections.push("");

      // Current goals from me.md
      const goals = await extractCurrentGoals();
      if (!goals.startsWith("(")) {
        sections.push("## Current Goals");
        sections.push(goals);
        sections.push("");
      }

      // Active projects from work.md
      const projects = await extractActiveProjects();
      if (!projects.startsWith("(")) {
        sections.push("## Active Projects");
        sections.push(projects);
        sections.push("");
      }

      // Recent promoted facts (last 7 days) — reduced budget
      try {
        const facts = sm.getRecentPromotedFacts(7);
        if (facts.length > 0) {
          sections.push("## Recent Memory Promotions (7d)");
          for (const fact of facts.slice(0, 8)) {
            const date = fact.promotedAt.slice(0, 10);
            const target = fact.targetFile;
            const snippet = fact.content.length > 100
              ? fact.content.slice(0, 100) + "..."
              : fact.content;
            sections.push(`- [${date}] → ${target}: ${snippet}`);
          }
          sections.push("");
        }
      } catch {
        // promoted_facts table may not exist yet
      }

      // Active plans
      const plansDir = PATHS.plans;
      if (existsSync(plansDir)) {
        try {
          const planFiles = readdirSync(plansDir)
            .filter(f => f.endsWith(".md") && f !== "archive");
          if (planFiles.length > 0) {
            sections.push("## Active Plans");
            for (const file of planFiles.slice(0, 10)) {
              const name = file.replace(/\.md$/, "").replace(/-/g, " ");
              sections.push(`- ${name}`);
            }
            sections.push("");
          }
        } catch {
          // plans dir read error
        }
      }

      // Pending outcome checks
      try {
        const pending = sm.getDb().prepare(`
          SELECT source_title, check_at
          FROM outcome_checks
          WHERE status = 'pending' AND check_at <= datetime('now', '+7 days')
          ORDER BY check_at ASC LIMIT 5
        `).all() as Array<{ source_title: string; check_at: string }>;

        if (pending.length > 0) {
          sections.push("## Pending Outcome Checks");
          for (const oc of pending) {
            sections.push(`- [${oc.check_at.slice(0, 10)}] ${oc.source_title}`);
          }
          sections.push("");
        }
      } catch {
        // outcome_checks table may not exist
      }

      // Build Homer zone content, enforce line limit
      let homerContent = sections.join("\n");
      const lines = homerContent.split("\n");
      if (lines.length > HOMER_MAX_LINES) {
        homerContent = lines.slice(0, HOMER_MAX_LINES).join("\n") + "\n\n<!-- Truncated -->";
      }

      // Write to each target project dir
      const results: string[] = [];
      for (const outputDir of TARGET_DIRS) {
        if (!existsSync(outputDir)) {
          mkdirSync(outputDir, { recursive: true });
        }

        const memoryPath = join(outputDir, "MEMORY.md");
        const merged = mergeWithExisting(homerContent, memoryPath);

        // Atomic write: temp file with unique suffix + rename
        const tmpPath = memoryPath + `.tmp.${process.pid}`;
        writeFileSync(tmpPath, merged, "utf-8");
        renameSync(tmpPath, memoryPath);

        const lineCount = merged.split("\n").length;
        results.push(`${outputDir}: ${lineCount} lines`);

        // Clean up stale homer-context.md
        const staleFile = join(outputDir, "homer-context.md");
        if (existsSync(staleFile)) {
          unlinkSync(staleFile);
          logger.info({ staleFile }, "Deleted stale homer-context.md");
        }
      }

      logger.info({ targets: results }, "Context bridge: MEMORY.md generated");

      return {
        success: true,
        output: `Generated MEMORY.md → ${results.join(", ")}`,
      };
    } finally {
      if (ownSm) sm.close();
    }
  } catch (error) {
    const msg = error instanceof Error ? error.message : String(error);
    logger.error({ error: msg }, "Context bridge failed");
    return { success: false, output: "", error: msg };
  }
}

// CLI entry point for direct tsx/node execution (used by hook fallback)
const isMain = import.meta.url === `file://${process.argv[1]}`
  || process.argv[1]?.endsWith("/context-bridge.js");
if (isMain) {
  runContextBridge().then(r => {
    console.log(r.output);
    process.exit(r.success ? 0 : 1);
  });
}
