/**
 * Context Bridge — keeps Claude Code auto-memory aligned with Homer memory.
 *
 * Generates:
 * - a compact Homer-managed block inside MEMORY.md
 * - deterministic topic files for fuller detail
 *
 * The bridge is a cache, not the source of truth. Homer memory (`~/memory/*.md`
 * plus `homer.db`) remains canonical. This job only refreshes Claude Code's
 * startup-oriented index when the underlying Homer context has materially
 * changed.
 */

import {
  writeFileSync,
  readFileSync,
  mkdirSync,
  existsSync,
  renameSync,
  readdirSync,
  unlinkSync,
} from "fs";
import { join } from "path";
import { extractCurrentGoals, extractActiveProjects } from "../shared-context.js";
import { executeClaudeCommand } from "../../executors/claude.js";
import { hashContextBridgeValue } from "../../state/context-bridge-state.js";
import { StateManager } from "../../state/manager.js";
import { logger } from "../../utils/logger.js";
import { PATHS } from "../../config/paths.js";

const HOMER_START = "<!-- HOMER:START — auto-generated by Homer daemon, do not edit -->";
const HOMER_END = "<!-- HOMER:END -->";
const HOMER_TARGET_LINES = 50;
const HOMER_MAX_LINES = 60;
const CURATION_TIMEOUT_MS = 120_000;
const CONTEXT_BRIDGE_MODEL = "sonnet";
const PERIODIC_TRIGGER_SOURCES = new Set(["context-bridge-refresh"]);

const TARGET_DIRS = [
  PATHS.autoMemoryDir,
  join(PATHS.claudeDir, "projects/-Users-yj-homer/memory"),
];

export interface RawContextData {
  goals: string;
  projects: string;
  recentFacts: string[];
  activePlans: string[];
  pendingOutcomes: string[];
  recentSessions: string[];
}

export interface TopicFile {
  fileName: string;
  content: string;
}

export interface RunContextBridgeOptions {
  triggerSource?: string;
  targetDirs?: readonly string[];
  forceRefresh?: boolean;
}

function wrapWithSentinels(content: string): string {
  return `${HOMER_START}\n${content}\n${HOMER_END}`;
}

export function mergeWithExisting(homerContent: string, memoryPath: string): string {
  if (!existsSync(memoryPath)) return wrapWithSentinels(homerContent);

  const existing = readFileSync(memoryPath, "utf-8");
  const startIdx = existing.indexOf(HOMER_START);
  const endIdx = existing.lastIndexOf(HOMER_END);

  let claudeContent: string;
  if (startIdx >= 0 && endIdx >= 0) {
    const before = existing.slice(0, startIdx).trim();
    claudeContent = before || "";
  } else {
    claudeContent = existing.trim();
  }

  return wrapWithSentinels(homerContent) + (claudeContent ? "\n\n" + claudeContent : "");
}

function isUnavailableBlock(text: string): boolean {
  const trimmed = text.trim();
  return trimmed.length === 0 || trimmed.startsWith("(");
}

function truncateLine(value: string, max: number = 140): string {
  const trimmed = value.replace(/\s+/g, " ").trim();
  if (trimmed.length <= max) return trimmed;
  return `${trimmed.slice(0, max - 3).trim()}...`;
}

function dedupeItems(values: string[]): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const value of values) {
    const key = value.toLowerCase();
    if (seen.has(key)) continue;
    seen.add(key);
    out.push(value);
  }
  return out;
}

function extractSummaryItems(text: string, limit: number): string[] {
  if (isUnavailableBlock(text)) return [];

  const items: string[] = [];
  for (const rawLine of text.split("\n")) {
    let line = rawLine.trim();
    if (!line) continue;
    if (/^#{1,6}\s/.test(line)) continue;
    line = line.replace(/^[-*]\s+/, "").replace(/^\d+\.\s+/, "").trim();
    if (!line || /^[_-]{3,}$/.test(line)) continue;
    items.push(truncateLine(line));
    if (items.length >= limit) break;
  }

  return dedupeItems(items);
}

function renderSection(title: string, items: string[], emptyText: string): string[] {
  const lines = [`## ${title}`];
  if (items.length === 0) {
    lines.push(emptyText);
  } else {
    for (const item of items) {
      lines.push(`- ${item}`);
    }
  }
  lines.push("");
  return lines;
}

function renderTopicDocument(
  title: string,
  description: string,
  body: string,
  emptyText: string,
): string {
  const normalizedBody = body.trim();
  const lines = [`# ${title}`, "", description, ""];
  if (normalizedBody && !isUnavailableBlock(normalizedBody)) {
    lines.push(normalizedBody);
  } else {
    lines.push(emptyText);
  }
  return `${lines.join("\n").trim()}\n`;
}

function renderTrackerTopic(data: RawContextData): string {
  const lines: string[] = [
    "# Homer Tracker",
    "",
    "Deterministic tracker snapshot generated from Homer memory state.",
    "",
    ...renderSection("Recent Promotions", data.recentFacts.slice(0, 12), "_No recent promotions._"),
    ...renderSection("Active Plans", data.activePlans.slice(0, 10), "_No active plans._"),
    ...renderSection("Pending Outcome Checks", data.pendingOutcomes.slice(0, 8), "_No upcoming outcome checks._"),
    ...renderSection("Recent Sessions", data.recentSessions.slice(0, 10), "_No recent session summaries._"),
  ];

  return `${lines.join("\n").trim()}\n`;
}

export function renderTopicFiles(data: RawContextData): TopicFile[] {
  return [
    {
      fileName: "homer-goals.md",
      content: renderTopicDocument(
        "Homer Goals",
        "Deterministic goals snapshot generated from Homer memory state.",
        data.goals,
        "_No current goals extracted._",
      ),
    },
    {
      fileName: "homer-projects.md",
      content: renderTopicDocument(
        "Homer Projects",
        "Deterministic project snapshot generated from Homer memory state.",
        data.projects,
        "_No active projects extracted._",
      ),
    },
    {
      fileName: "homer-tracker.md",
      content: renderTrackerTopic(data),
    },
  ];
}

function buildPriorityItems(data: RawContextData): string[] {
  return dedupeItems([
    ...data.pendingOutcomes.slice(0, 3).map((item) => `Follow up: ${truncateLine(item, 120)}`),
    ...data.activePlans.slice(0, 3).map((item) => `Plan: ${truncateLine(item, 120)}`),
    ...data.recentSessions.slice(0, 2).map((item) => `Recent session: ${truncateLine(item, 120)}`),
  ]).slice(0, 5);
}

function enforceLineCap(content: string, maxLines: number): string {
  const trimmed = content.trim();
  const lines = trimmed.split("\n");
  if (lines.length <= maxLines) return trimmed;
  return lines.slice(0, maxLines).join("\n").trim();
}

export function buildMechanicalIndex(data: RawContextData, topicFiles: TopicFile[]): string {
  const updatedAt = new Date().toISOString();
  const goals = extractSummaryItems(data.goals, 4);
  const projects = extractSummaryItems(data.projects, 4);
  const priorities = buildPriorityItems(data);

  const lines: string[] = [
    `<!-- Updated: ${updatedAt} -->`,
    "# Homer Context",
    "",
    ...renderSection("Current Priorities", priorities, "_No urgent changes surfaced._"),
    ...renderSection("Goals", goals, "_See homer-goals.md for detail._"),
    ...renderSection("Active Projects", projects, "_See homer-projects.md for detail._"),
    "## Topic Files",
  ];

  for (const file of topicFiles) {
    lines.push(`- ${file.fileName}`);
  }
  lines.push("");
  lines.push("## Notes");
  lines.push("- Use homer-tracker.md for promotions, plans, outcome checks, and recent sessions.");

  return enforceLineCap(lines.join("\n"), HOMER_MAX_LINES);
}

function stripCodeFences(content: string): string {
  return content
    .replace(/^```(?:markdown)?\s*/i, "")
    .replace(/\s*```$/i, "")
    .trim();
}

export function normalizeBridgeOutputForHash(content: string): string {
  return content.replace(/<!-- Updated: .*? -->/g, "<!-- Updated: -->").trim();
}

function buildOutputHash(homerContent: string, topicFiles: TopicFile[]): string {
  return hashContextBridgeValue({
    homerContent: normalizeBridgeOutputForHash(homerContent),
    topicFiles: topicFiles.map((file) => ({
      fileName: file.fileName,
      content: file.content.trim(),
    })),
  });
}

async function collectRawData(sm: StateManager): Promise<RawContextData> {
  const goals = await extractCurrentGoals();
  const projects = await extractActiveProjects();

  const recentFacts: string[] = [];
  try {
    const facts = sm.getRecentPromotedFacts(7);
    for (const fact of facts.slice(0, 12)) {
      const date = fact.promotedAt.slice(0, 10);
      recentFacts.push(`[${date}] ${fact.targetFile}: ${truncateLine(fact.content, 180)}`);
    }
  } catch { /* knowledge_claims query failed — non-fatal */ }

  const activePlans: string[] = [];
  if (existsSync(PATHS.plans)) {
    try {
      const planFiles = readdirSync(PATHS.plans)
        .filter((file) => file.endsWith(".md"))
        .slice(0, 10);
      for (const file of planFiles) {
        activePlans.push(file.replace(/\.md$/, "").replace(/-/g, " "));
      }
    } catch {
      // best-effort only
    }
  }

  const pendingOutcomes: string[] = [];
  try {
    const pending = sm.getDb().prepare(`
      SELECT source_title, check_at
      FROM outcome_checks
      WHERE status = 'pending'
        AND check_at <= datetime('now', '+7 days')
      ORDER BY check_at ASC
      LIMIT 6
    `).all() as Array<{ source_title: string; check_at: string }>;

    for (const item of pending) {
      pendingOutcomes.push(`[${item.check_at.slice(0, 10)}] ${truncateLine(item.source_title, 140)}`);
    }
  } catch {
    // best-effort only
  }

  const recentSessions: string[] = [];
  try {
    const sessions = sm.getDb().prepare(`
      SELECT title, project, substr(summary, 1, 180) as summary
      FROM session_summaries
      WHERE is_sub_agent = 0
        AND started_at > datetime('now', '-48 hours')
      ORDER BY started_at DESC
      LIMIT 8
    `).all() as Array<{ title: string | null; project: string | null; summary: string | null }>;

    for (const session of sessions) {
      const project = session.project ? `[${session.project}] ` : "";
      const title = session.title?.trim() || "untitled";
      if (title.startsWith("<") || title.startsWith("session-flush")) continue;
      const summary = session.summary?.trim() || "";
      recentSessions.push(truncateLine(`${project}${title}: ${summary}`, 180));
    }
  } catch {
    // best-effort only
  }

  return { goals, projects, recentFacts, activePlans, pendingOutcomes, recentSessions };
}

async function buildCuratedIndex(
  data: RawContextData,
  topicFiles: TopicFile[],
): Promise<string | null> {
  const updatedAt = new Date().toISOString();
  const prompt = `You are Homer's context-bridge. Write the Homer-managed index block that sits at the top of Claude Code MEMORY.md.

Constraints:
- Output markdown only. No preamble. No code fences.
- Target ${HOMER_TARGET_LINES} lines. Hard maximum ${HOMER_MAX_LINES} lines.
- First line must be exactly: <!-- Updated: ${updatedAt} -->
- Second non-empty line must be: # Homer Context
- This is a startup index, not a dump. Keep it compact.
- Include:
  1. 3-5 current priorities
  2. short goals summary
  3. short active-project summary
  4. urgent outcome checks / next actions if any
  5. a Topic Files section that lists homer-goals.md, homer-projects.md, homer-tracker.md
- Do not restate long detail that already belongs in the topic files.

Raw data:

## Goals
${data.goals.startsWith("(") ? "Not available" : data.goals}

## Active Projects
${data.projects.startsWith("(") ? "Not available" : data.projects}

## Recent Promotions
${data.recentFacts.length > 0 ? data.recentFacts.join("\n") : "None"}

## Active Plans
${data.activePlans.length > 0 ? data.activePlans.map((item) => `- ${item}`).join("\n") : "None"}

## Pending Outcome Checks
${data.pendingOutcomes.length > 0 ? data.pendingOutcomes.map((item) => `- ${item}`).join("\n") : "None"}

## Recent Sessions
${data.recentSessions.length > 0 ? data.recentSessions.join("\n") : "None"}

Topic files being written alongside this index:
${topicFiles.map((file) => `\n### ${file.fileName}\n${file.content}`).join("\n")}
`;

  try {
    const result = await executeClaudeCommand(prompt, {
      cwd: process.env.HOME ?? "/Users/yj",
      model: CONTEXT_BRIDGE_MODEL,
      timeout: CURATION_TIMEOUT_MS,
    });

    if (result.exitCode !== 0 || !result.output) {
      logger.warn(
        { exitCode: result.exitCode },
        "Context bridge Sonnet curation failed, falling back to mechanical index",
      );
      return null;
    }

    let content = stripCodeFences(result.output);
    const headerIdx = content.indexOf("# Homer Context");
    if (headerIdx < 0) {
      logger.warn("Context bridge output missing header, falling back");
      return null;
    }

    content = content.slice(headerIdx).trim();
    content = content.replace(/<!-- Updated: .*? -->\s*/g, "").trim();
    content = `<!-- Updated: ${updatedAt} -->\n${content}`;
    content = enforceLineCap(content, HOMER_MAX_LINES);

    logger.info(
      { lines: content.split("\n").length },
      "Context bridge curated with Sonnet",
    );

    return content;
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    logger.warn({ error: message }, "Context bridge curation threw");
    return null;
  }
}

function writeFileIfChanged(filePath: string, content: string): boolean {
  if (existsSync(filePath)) {
    const existing = readFileSync(filePath, "utf-8");
    if (existing === content) return false;
  }

  const tmpPath = `${filePath}.tmp.${process.pid}`;
  writeFileSync(tmpPath, content, "utf-8");
  renameSync(tmpPath, filePath);
  return true;
}

function writeBridgeFiles(
  targetDirs: readonly string[],
  homerContent: string,
  topicFiles: TopicFile[],
): string[] {
  const results: string[] = [];

  for (const outputDir of [...new Set(targetDirs)]) {
    if (!existsSync(outputDir)) {
      mkdirSync(outputDir, { recursive: true });
    }

    let changedFiles = 0;

    for (const topicFile of topicFiles) {
      const topicPath = join(outputDir, topicFile.fileName);
      if (writeFileIfChanged(topicPath, topicFile.content)) {
        changedFiles++;
      }
    }

    const memoryPath = join(outputDir, "MEMORY.md");
    const merged = mergeWithExisting(homerContent, memoryPath);
    if (writeFileIfChanged(memoryPath, merged)) {
      changedFiles++;
    }

    const staleFile = join(outputDir, "homer-context.md");
    if (existsSync(staleFile)) {
      unlinkSync(staleFile);
      changedFiles++;
      logger.info({ staleFile }, "Deleted stale homer-context.md");
    }

    results.push(`${outputDir}: ${changedFiles} file(s) updated`);
  }

  return results;
}

export async function runContextBridge(
  stateManager?: StateManager,
  options: RunContextBridgeOptions = {},
): Promise<{ success: boolean; output: string; error?: string }> {
  let sm: StateManager | null = null;
  let ownSm = false;
  let triggerSource = options.triggerSource ?? "manual";
  let sourceHash: string | null = null;

  try {
    sm = stateManager ?? new StateManager(PATHS.db);
    ownSm = !stateManager;

    const state = sm.getContextBridgeState();
    const pipelineDirty = sm.isPipelineDirty("context_bridge");
    if (!options.forceRefresh && PERIODIC_TRIGGER_SOURCES.has(triggerSource) && state.dirty === 0 && !pipelineDirty) {
      return {
        success: true,
        output: `Context bridge skipped (${triggerSource}) — state clean`,
      };
    }

    sm.recordContextBridgeStart(triggerSource);

    const data = await collectRawData(sm);
    sourceHash = hashContextBridgeValue(data);

    if (!options.forceRefresh && state.sourceHash === sourceHash) {
      sm.recordContextBridgeResult({
        triggerSource,
        sourceHash,
        outputHash: state.outputHash,
        dirty: false,
        method: "unchanged-source",
      });
      sm.clearPipelineDirty("context_bridge");
      return {
        success: true,
        output: `Context bridge skipped (${triggerSource}) — source unchanged`,
      };
    }

    const topicFiles = renderTopicFiles(data);
    let homerContent = await buildCuratedIndex(data, topicFiles);
    let method = "claude-curated:sonnet";

    if (!homerContent) {
      homerContent = buildMechanicalIndex(data, topicFiles);
      method = "mechanical-fallback";
    }

    const outputHash = buildOutputHash(homerContent, topicFiles);
    if (!options.forceRefresh && state.outputHash === outputHash) {
      sm.recordContextBridgeResult({
        triggerSource,
        sourceHash,
        outputHash,
        dirty: false,
        method: "unchanged-output",
      });
      sm.clearPipelineDirty("context_bridge");
      return {
        success: true,
        output: `Context bridge skipped (${triggerSource}) — output unchanged`,
      };
    }

    const targetDirs = options.targetDirs ?? TARGET_DIRS;
    const results = writeBridgeFiles(targetDirs, homerContent, topicFiles);

    sm.recordContextBridgeResult({
      triggerSource,
      sourceHash,
      outputHash,
      dirty: false,
      method,
    });

    // Clear pipeline dirty flag
    sm.clearPipelineDirty("context_bridge");

    logger.info({ targets: results, method, triggerSource }, "Context bridge refreshed");

    return {
      success: true,
      output: `Updated context bridge (${method}) -> ${results.join(", ")}`,
    };
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    if (sm) {
      sm.recordContextBridgeResult({
        triggerSource,
        sourceHash,
        dirty: true,
        method: null,
        error: message,
      });
    }
    logger.error({ error: message, triggerSource }, "Context bridge failed");
    return { success: false, output: "", error: message };
  } finally {
    if (ownSm && sm) {
      sm.close();
    }
  }
}

const isMain = import.meta.url === `file://${process.argv[1]}`
  || process.argv[1]?.endsWith("/context-bridge.js");

if (isMain) {
  runContextBridge().then((result) => {
    console.log(result.output);
    process.exit(result.success ? 0 : 1);
  });
}
